server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    username: root
    password: ""
    url: jdbc:mysql://localhost:3306/product
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  tracing:
    sampling:
      probability: 1.0